### ISSUE TITLE
Need Help: invalid utf-8 sequence of 1 bytes from index 1

### ISSUE THREAD

**Issue by imzlh** [sigmaSd/deno-pty-ffi#5]
![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/94f092fd-0d9b-46d5-b695-42b284399934)

![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/5cf20c80-e8b7-4eb3-b15a-832c0007663a)

I write a wrapper using StreamAPI.I'm not good at RUST,so I only changed some logic(typescript).
Strangely,When I tried to writeIn UInt8Array( A Wrap Character ), "invalid utf-8 sequence of 1 bytes from index 1"
Please tell me what shold I do,thanks.

My branch: https://github.com/imzlh/deno-pty-ffi

**Comment by sigmaSd** [comment]
When I see such errors I suspect that the cstring was not encoded correctly, 
- the easy way to encode cstring is to append "\0" to it, but what if the string already have a null byte, maybe you're missing this somewhere

I tried the example.ts , it seemed to work for me, which character do I need to input to have this bug ?

**Comment by Shougo** [comment]
@sigmaSd Can you test the script?  It is failed.

```typescript
import { Pty } from "jsr:@sigma/pty-ffi";

const pty = new Pty({
  cmd: "echo",
  args: ["日本語"],
  env: [],
});

// executs ls -la repedetly and shows output
while (true) {
  const { data, done } = pty.read();
  if (done) break;
  console.log(data);
  await new Promise((r) => setTimeout(r, 100));
}
```

```
error: Uncaught (in promise) Error: EOF while parsing a string at line 1 column 39
    if (result === -1) throw new Error(decodeCstring(ptr));
                             ^
    at new Pty (https://jsr.io/@sigma/pty-ffi/0.28.0/src/mod.ts:32:30)
    at file:///home/shougo/work/test_pty.ts:3:13
    at eventLoopTick (ext:core/01_core.js:178:7)
```

**Comment by sigmaSd** [comment]
should be fixed in 0.32.0
